// Types for importing images (e.g. `import shot from "./shot.png"`). next-env.d.ts declares
// these too, but it is generated by a build and not committed, so CI's type check needs this.
/// <reference types="next/image-types/global" />
